
Paths:
  Substitutions:
  # Patterns given between ** ** can be replaced dynamically (see HelperFunctions.py)
    read_data_dir: Y:/**siteID**/
    write_data_dir: C:/Users/labuser/EP_API_Testing/**siteID**/
    
  raw_path: '**read_data_dir**/raw/**year**/**month**/'
  biomet_path: '**read_data_dir**/biomet/**year**/biomet.csv'
  # processed data output
  meta_dir: '**write_data_dir**/metadata/'
  eddypro_output: '**write_data_dir**/EP_Test_Runs/'
  eddypro_installation: C:/Program Files/LI-COR/EddyPro-7.0.9/bin/

filenames:
  file_inventory: fileInventory.csv
  raw_means: rawMeans.csv
  dynamic_metadata: dynamicMetadata.csv
  site_setup: siteSetup.csv
  headers: Headers.csv
  calibration_parameters: calibrationsParameters.csv
  eddypro_rp: eddypro_rp.exe
  eddypro_fcc: eddypro_fcc.exe

templates:
  variableList: ini_files/VariableNames.ini

# delimiter_key:
#   comma: ','
#   tab: '\t'


# ghg:
#   ; Regex search for dates in filename
#   search: ([0-9]{4}\-[0-9]{2}\-[0-9]{2}T[0-9]{6})
#   format: '%%Y-%%m-%%dT%%H%%M%%S'
#   ep_date_pattern: yyyy-mm-ddTHHMM??

# dat:
#   search: ([0-9]{4}\_[0-9]{2}\_[0-9]{2}\_[0-9]{4})
#   format: '%%Y_%%m_%%d_%%H%%M'
#   ep_date_pattern: yyyy_mm_dd_HHMM

# biom_timestamp:
#   name: TIMESTAMP_1
#   format: '%%Y-%%m-%%d %%H%%M'

Calibration_Info:
  # Set to True to include (only where it exists)
  # Skipping will speed up
  readCal:  True